### ISSUE TITLE
Use Cases (Sort, Retrieve, Print/Export) Megs

### ISSUE THREAD

**Issue by LazECU** [S18MIS4173Team9/Team9#4]

**Comment by hancockm15** [comment]
The sort and print/export use cases are completed. We agreed that creating the retrieve use case would be redundant with the search use case. 
[Export Use Case.docx](https://github.com/S18MIS4173Team9/Team9/files/1716623/Export.Use.Case.docx)
[Sort By Use Case.docx](https://github.com/S18MIS4173Team9/Team9/files/1716624/Sort.By.Use.Case.docx)
